steps:
    - name: 'gcr.io/cloud-builders/docker'
      id: A
    # COnstruction de l'image
      args: ['build', '-t', 'gcr.io/cellular-axon-325108/flask-hello-jules-ci-cd:latest','.']
    - name: 'gcr.io/google.com/cloudsdktool/sloud-sdk'
      waitfor: [A]
      entrypoint: gcloud
      args: ['run', 'depoloy','test-flask-hello-jules-ci-cd','--image' ,'gcr.io/cellular-axon-325108/flask-hello-jules-ci-cd:latest','--region','europe-west3','--port','80']
# Push de l'image
images: [gcr.io/cellular-axon-325108/flask-hello-jules-ci-cd:latest]
